import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "About Page",
//   description: "Generated by create next app",
// };

export default function AboutLayout({ children }) {
  return (
    <main className="ml-5">
      <nav className="pt-5 pb-20">
        <ul className="flex space-x-5">
          <li>
            <Link href="/about/mission">Mission</Link>
          </li>
          <li>
            <Link href="/about/vision">Vision</Link>
          </li>
        </ul>
      </nav>
      {children}
    </main>
  );
}
