import React from "react";

// export const metadata = {
//   title: "About Page",
//   description: "Generated by create next app",

export default function About() {
  return (
    <main>
      <h1>About Page</h1>
    </main>
  );
}
